services:
  opencti-dev-redis:
    container_name: opencti-dev-redis
    image: redis:7.4.4
    restart: unless-stopped
    ports:
      - "6379:6379"
  opencti-dev-elasticsearch:
    container_name: opencti-dev-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.2
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
  opencti-dev-kibana:
    container_name: opencti-dev-kibana
    image: docker.elastic.co/kibana/kibana:8.18.2
    environment:
      - ELASTICSEARCH_HOSTS=http://opencti-dev-elasticsearch:9200
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - opencti-dev-elasticsearch
  opencti-dev-minio:
    container_name: opencti-dev-minio
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: unless-stopped
  opencti-dev-rabbitmq:
    container_name: opencti-dev-rabbitmq
    image: rabbitmq:4.1-management
    volumes:
      - type: bind
        source: rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
  opencti-dev-platform:
    container_name: opencti-dev-platform
    image: opencti/platform:6.7.1
    restart: unless-stopped
    depends_on:
      - opencti-dev-redis
      - opencti-dev-elasticsearch
      - opencti-dev-minio
      - opencti-dev-rabbitmq
    environment:
      - APP__PORT=8080
      - APP__BASE_URL=http://localhost:8080
      - REDIS__HOST=opencti-dev-redis
      - ELASTICSEARCH__URL=http://opencti-dev-elasticsearch:9200
      - MINIO__ENDPOINT=opencti-dev-minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=opencti-dev-rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
    ports:
      - "8080:8080"
    env_file:
      - .env


